######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 1 19:40:56 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .

CODE = $(HOME)/code
INCLUDEPATH += . $${CODE}/include

# Input
HEADERS += votingspace.hh rf_ismreco.hh
SOURCES += main.cc votingspace.cc rf_ismreco.cc 


QT_LIBS      =  -lQtTools2
IMGDB_LIBS   = -lImgDB
#PCCV_LIBS    = -lrgbdisp 
IMAGE_LIBS   = -limage2 -lGrayImage2 -lRGBImage2 -lGaussDeriv2 -lCanny2 -lMorphology2 
SCALE_LIBS   = -lScaleSpace2 -lInterestPts2 -lPatchExtraction6
FEATURE_LIBS = -lFeatures2 -lPCA2 -lMath2 -lMatrix2 -lChiSquare2 -lNNSearch3 -lCluster3 -lHistogram2 -lEdgeSIFT2 #-lChamfer
RANDOMFOREST_LIBS = -lRandomForest 
#RECO_LIBS    = -lCodebook2 -lVotingSpace2 -lISM2
#OTHER_LIBS     = -lHelpers -lIDL -lOrientationPlanes #-lewidgets
#STD_LIBS     = -lm -lstdc++
LIBS += -L$${CODE}/lib/i686 $${QT_LIBS}  $${IMAGE_LIBS} $${PCCV_LIBS} $${SCALE_LIBS} $${FEATURE_LIBS} $${RANDOMFOREST_LIBS}

QT += qt3support
