######################################################################
# Automatically generated by qmake (1.07a) Sun Jan 20 22:35:20 2013
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += Hello.cc
